# This workflow will build a package using Maven and then publish it to
#  qbic-repo.qbic.uni-tuebingen.de packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Nexus Package

on:
  release:
    types: [created]
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to QBiC Nexus Repository
      run: mvn --quiet --activate-profiles development-build,!release-build --settings $GITHUB_WORKSPACE/.github.settings.xml deploy
      env:
        MAVEN_REPO_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        MAVEN_REPO_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
